import requests
import time
import sys
import pymysql
import datetime
sys.path.insert(0, './common')
from utils import connect_to_db
gap = 0.5


def has_accessory(punk, accessory_name):
    accessory = [x for x in punk["traits"] if x["value"] == accessory_name]
    return True if len(accessory) > 0 else False


def lambda_handler(event, context):
    conn = connect_to_db()
    for id in range(1, 10001):
        print('Importing punk', id)
        url = "https://api.opensea.io/api/v1/asset/0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb/" + str(id)
        punk = requests.request("GET", url).json()

        type_trait = [x for x in punk["traits"] if x["trait_type"] == "type"]
        type = type_trait[0]["value"] if len(type_trait) > 0 else None

        attribute_list = [
            has_accessory(punk, "Beanie"),
            has_accessory(punk, "Choker"),
            has_accessory(punk, "Pilot Helmet"),
            has_accessory(punk, "Tiara"),
            has_accessory(punk, "Orange Side"),
            has_accessory(punk, "Buck Teeth"),
            has_accessory(punk, "Welding Goggles"),
            has_accessory(punk, "Pigtails"),
            has_accessory(punk, "Pink With Hat"),
            has_accessory(punk, "Top Hat"),
            has_accessory(punk, "Spots"),
            has_accessory(punk, "Rosy Cheeks"),
            has_accessory(punk, "Blonde Short"),
            has_accessory(punk, "Wild White Hair"),
            has_accessory(punk, "Cowboy Hat"),
            has_accessory(punk, "Wild Blonde"),
            has_accessory(punk, "Straight Hair Blonde"),
            has_accessory(punk, "Big Beard"),
            has_accessory(punk, "Red Mohawk"),
            has_accessory(punk, "Half Shaved"),
            has_accessory(punk, "Blonde Bob"),
            has_accessory(punk, "Vampire Hair"),
            has_accessory(punk, "Clown Hair Green"),
            has_accessory(punk, "Straight Hair Dark"),
            has_accessory(punk, "Straight Hair"),
            has_accessory(punk, "Silver Chain"),
            has_accessory(punk, "Dark Hair"),
            has_accessory(punk, "Purple Hair"),
            has_accessory(punk, "Gold Chain"),
            has_accessory(punk, "Medical Mask"),
            has_accessory(punk, "Tassle Hat"),
            has_accessory(punk, "Fedora"),
            has_accessory(punk, "Police Cap"),
            has_accessory(punk, "Clown Nose"),
            has_accessory(punk, "Smile"),
            has_accessory(punk, "Cap Forward"),
            has_accessory(punk, "Hoodie"),
            has_accessory(punk, "Front Beard Dark"),
            has_accessory(punk, "Frown"),
            has_accessory(punk, "Purple Eye Shadow"),
            has_accessory(punk, "Handlebars"),
            has_accessory(punk, "Blue Eye Shadow"),
            has_accessory(punk, "Green Eye Shadow"),
            has_accessory(punk, "Vape"),
            has_accessory(punk, "Front Beard"),
            has_accessory(punk, "Chinstrap"),
            has_accessory(punk, "3D Glasses"),
            has_accessory(punk, "Luxurious Beard"),
            has_accessory(punk, "Mustache"),
            has_accessory(punk, "Normal Beard Black"),
            has_accessory(punk, "Normal Beard"),
            has_accessory(punk, "Eye Mask"),
            has_accessory(punk, "Goat"),
            has_accessory(punk, "Do-rag"),
            has_accessory(punk, "Shaved Head"),
            has_accessory(punk, "Muttonchops"),
            has_accessory(punk, "Peak Spike"),
            has_accessory(punk, "Pipe"),
            has_accessory(punk, "VR"),
            has_accessory(punk, "Cap"),
            has_accessory(punk, "Small Shades"),
            has_accessory(punk, "Clown Eyes Green"),
            has_accessory(punk, "Clown Eyes Blue"),
            has_accessory(punk, "Headband"),
            has_accessory(punk, "Crazy Hair"),
            has_accessory(punk, "Knitted Cap"),
            has_accessory(punk, "Mohawk Dark"),
            has_accessory(punk, "Mohawk"),
            has_accessory(punk, "Mohawk Thin"),
            has_accessory(punk, "Frumpy Hair"),
            has_accessory(punk, "Wild Hair"),
            has_accessory(punk, "Messy Hair"),
            has_accessory(punk, "Eye Patch"),
            has_accessory(punk, "Stringy Hair"),
            has_accessory(punk, "Bandana"),
            has_accessory(punk, "Classic Shades"),
            has_accessory(punk, "Shadow Beard"),
            has_accessory(punk, "Regular Shades"),
            has_accessory(punk, "Horned Rim Glasses"),
            has_accessory(punk, "Big Shades"),
            has_accessory(punk, "Nerd Glasses"),
            has_accessory(punk, "Black Lipstick"),
            has_accessory(punk, "Mole"),
            has_accessory(punk, "Purple Lipstick"),
            has_accessory(punk, "Hot Lipstick"),
            has_accessory(punk, "Cigarette"),
            has_accessory(punk, "Earring")
        ]
        attribute_count = sum(attribute_list)

        with conn.cursor() as cur:
            sql = f"""
            INSERT INTO punks(
                id,
                type,
                attribute_count,
                external_url,
                opensea_url,
                has_beanie,
                has_choker,
                has_pilot_helmet,
                has_tiara,
                has_orange_side,
                has_buck_teeth,
                has_welding_goggles,
                has_pigtails,
                has_pink_with_hat,
                has_top_hat,
                has_spots,
                has_rosy_cheeks,
                has_blonde_short,
                has_wild_white_hair,
                has_cowboy_hat,
                has_wild_blonde,
                has_straight_hair_blonde,
                has_big_beard,
                has_red_mohawk,
                has_half_shaved,
                has_blonde_bob,
                has_vampire_hair,
                has_clown_hair_green,
                has_straight_hair_dark,
                has_straight_hair,
                has_silver_chain,
                has_dark_hair,
                has_purple_hair,
                has_gold_chain,
                has_medical_mask,
                has_tassle_hat,
                has_fedora,
                has_police_cap,
                has_clown_nose,
                has_smile,
                has_cap_forward,
                has_hoodie,
                has_front_beard_dark,
                has_frown,
                has_purple_eye_shadow,
                has_handlebars,
                has_blue_eye_shadow,
                has_green_eye_shadow,
                has_vape,
                has_front_beard,
                has_chinstrap,
                has_3d_glasses,
                has_luxurious_beard,
                has_mustache,
                has_normal_beard_black,
                has_normal_beard,
                has_eye_mask,
                has_goat,
                has_dorag,
                has_shaved_head,
                has_muttonchops,
                has_peak_spike,
                has_pipe,
                has_vr,
                has_cap,
                has_small_shades,
                has_clown_eyes_green,
                has_clown_eyes_blue,
                has_headband,
                has_crazy_hair,
                has_knitted_cap,
                has_mohawk_dark,
                has_mohawk,
                has_mohawk_thin,
                has_frumpy_hair,
                has_wild_hair,
                has_messy_hair,
                has_eye_patch,
                has_stringy_hair,
                has_bandana,
                has_classic_shades,
                has_shadow_beard,
                has_regular_shades,
                has_horned_rim_glasses,
                has_big_shades,
                has_nerd_glasses,
                has_black_lipstick,
                has_mole,
                has_purple_lipstick,
                has_hot_lipstick,
                has_cigarette,
                has_earring
            ) VALUES (
                {id},
                "{type}",
                {attribute_count},
                "{punk["external_link"]}",
                "{punk["permalink"]}",
                {has_accessory(punk, "Beanie")},
                {has_accessory(punk, "Choker")},
                {has_accessory(punk, "Pilot Helmet")},
                {has_accessory(punk, "Tiara")},
                {has_accessory(punk, "Orange Side")},
                {has_accessory(punk, "Buck Teeth")},
                {has_accessory(punk, "Welding Goggles")},
                {has_accessory(punk, "Pigtails")},
                {has_accessory(punk, "Pink With Hat")},
                {has_accessory(punk, "Top Hat")},
                {has_accessory(punk, "Spots")},
                {has_accessory(punk, "Rosy Cheeks")},
                {has_accessory(punk, "Blonde Short")},
                {has_accessory(punk, "Wild White Hair")},
                {has_accessory(punk, "Cowboy Hat")},
                {has_accessory(punk, "Wild Blonde")},
                {has_accessory(punk, "Straight Hair Blonde")},
                {has_accessory(punk, "Big Beard")},
                {has_accessory(punk, "Red Mohawk")},
                {has_accessory(punk, "Half Shaved")},
                {has_accessory(punk, "Blonde Bob")},
                {has_accessory(punk, "Vampire Hair")},
                {has_accessory(punk, "Clown Hair Green")},
                {has_accessory(punk, "Straight Hair Dark")},
                {has_accessory(punk, "Straight Hair")},
                {has_accessory(punk, "Silver Chain")},
                {has_accessory(punk, "Dark Hair")},
                {has_accessory(punk, "Purple Hair")},
                {has_accessory(punk, "Gold Chain")},
                {has_accessory(punk, "Medical Mask")},
                {has_accessory(punk, "Tassle Hat")},
                {has_accessory(punk, "Fedora")},
                {has_accessory(punk, "Police Cap")},
                {has_accessory(punk, "Clown Nose")},
                {has_accessory(punk, "Smile")},
                {has_accessory(punk, "Cap Forward")},
                {has_accessory(punk, "Hoodie")},
                {has_accessory(punk, "Front Beard Dark")},
                {has_accessory(punk, "Frown")},
                {has_accessory(punk, "Purple Eye Shadow")},
                {has_accessory(punk, "Handlebars")},
                {has_accessory(punk, "Blue Eye Shadow")},
                {has_accessory(punk, "Green Eye Shadow")},
                {has_accessory(punk, "Vape")},
                {has_accessory(punk, "Front Beard")},
                {has_accessory(punk, "Chinstrap")},
                {has_accessory(punk, "3D Glasses")},
                {has_accessory(punk, "Luxurious Beard")},
                {has_accessory(punk, "Mustache")},
                {has_accessory(punk, "Normal Beard Black")},
                {has_accessory(punk, "Normal Beard")},
                {has_accessory(punk, "Eye Mask")},
                {has_accessory(punk, "Goat")},
                {has_accessory(punk, "Do-rag")},
                {has_accessory(punk, "Shaved Head")},
                {has_accessory(punk, "Muttonchops")},
                {has_accessory(punk, "Peak Spike")},
                {has_accessory(punk, "Pipe")},
                {has_accessory(punk, "VR")},
                {has_accessory(punk, "Cap")},
                {has_accessory(punk, "Small Shades")},
                {has_accessory(punk, "Clown Eyes Green")},
                {has_accessory(punk, "Clown Eyes Blue")},
                {has_accessory(punk, "Headband")},
                {has_accessory(punk, "Crazy Hair")},
                {has_accessory(punk, "Knitted Cap")},
                {has_accessory(punk, "Mohawk Dark")},
                {has_accessory(punk, "Mohawk")},
                {has_accessory(punk, "Mohawk Thin")},
                {has_accessory(punk, "Frumpy Hair")},
                {has_accessory(punk, "Wild Hair")},
                {has_accessory(punk, "Messy Hair")},
                {has_accessory(punk, "Eye Patch")},
                {has_accessory(punk, "Stringy Hair")},
                {has_accessory(punk, "Bandana")},
                {has_accessory(punk, "Classic Shades")},
                {has_accessory(punk, "Shadow Beard")},
                {has_accessory(punk, "Regular Shades")},
                {has_accessory(punk, "Horned Rim Glasses")},
                {has_accessory(punk, "Big Shades")},
                {has_accessory(punk, "Nerd Glasses")},
                {has_accessory(punk, "Black Lipstick")},
                {has_accessory(punk, "Mole")},
                {has_accessory(punk, "Purple Lipstick")},
                {has_accessory(punk, "Hot Lipstick")},
                {has_accessory(punk, "Cigarette")},
                {has_accessory(punk, "Earring")}
            )
            ON DUPLICATE KEY UPDATE
                id=id
            """
            cur.execute(sql)
        conn.commit()
        time.sleep(gap)
    conn.close()


lambda_handler({}, {})
